#Create postgres Image for JSP Tutorial Application
FROM postgres:9.4

ENV TZ=UTC
ENV DB_IP=localhost
ENV DB_PORT=5432
ENV DB_USER=postgres
ENV DB_PASSWORD=admin
ENV DB_DBNAME=deployed-city-db
ENV POSTGRES_PASSWORD=admin

EXPOSE 5432